#!/bin/bash

git fetch --all
git merge upstream/master
make veryclean
make

if  [[ ! -f eduke32 ]] ; then
    echo 'Build failed!'
    exit
fi

cp -f eduke32 ./opk
rm -f *.opk
mksquashfs opk/* eduke32_v1.3_funkey-s.opk
md5sum eduke32
rm -f opk/eduke32
