#!/bin/bash

mkdir obj/

git fetch --all
git merge upstream/master
make veryclean
make

if  [[ ! -f eduke32 ]] ; then
    echo 'Build failed!'
    exit
fi

cp -f eduke32 ./opk
rm -f *.opk
mksquashfs opk/* eduke32_funkey-s.opk
rm -rf obj/
rm -f opk/eduke32
